# Generated by Django 5.0.9 on 2024-11-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('services', models.JSONField(blank=True, default=list, verbose_name=models.IntegerField())),
                ('init_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pet_name', models.CharField(max_length=100)),
                ('pet_type', models.IntegerField()),
                ('pet_breed', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
            ],
        ),
    ]
