# Generated by Django 5.0.9 on 2024-11-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='user_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='pet_type',
            field=models.CharField(max_length=100),
        ),
    ]
