# Generated by Django 5.0.9 on 2024-12-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserves', '0002_rename_pet_type_reserve_pet_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserve',
            name='total_reserva',
            field=models.IntegerField(default=20000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserve',
            name='services',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
