# Generated by Django 5.0.9 on 2024-11-07 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserves', '0003_alter_reserve_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='user_id',
        ),
    ]
