# Generated by Django 5.0.9 on 2024-10-31 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='asunto',
            field=models.TextField(default='Asunto predeterminado', max_length=100),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='mensaje',
            field=models.TextField(max_length=100),
        ),
    ]
