# Generated by Django 5.0.9 on 2024-12-05 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserves', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserve',
            old_name='pet_type',
            new_name='pet_size',
        ),
    ]
