# Generated by Django 5.0.9 on 2024-11-07 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_contacto_asunto_alter_contacto_mensaje'),
        ('users', '0005_alter_contacto_correo'),
    ]

    operations = [
    ]
